-- Welcome email template (sent when a company user is created)
INSERT INTO email_templates (name, subject, body_html, type, is_default)
SELECT
  'Bienvenida {{nombre_empresa}}',
  'Bienvenido a Alto Alcance CRM',
  '<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Bienvenido a Alto Alcance CRM</title></head><body style="font-family:-apple-system,BlinkMacSystemFont,''Segoe UI'',sans-serif;background-color:#f8fafc;margin:0;padding:40px 20px"><div style="max-width:560px;margin:0 auto;background:#ffffff;border-radius:12px;overflow:hidden;box-shadow:0 1px 3px rgba(0,0,0,0.1)"><div style="background:#0F172A;padding:32px 40px;text-align:center"><h1 style="color:#ffffff;font-size:22px;font-weight:700;margin:0">Alto Alcance CRM</h1><p style="color:#94a3b8;font-size:13px;margin:6px 0 0">Tu plataforma de gestión de leads</p></div><div style="padding:40px"><h2 style="color:#1e293b;font-size:20px;font-weight:700;margin:0 0 16px">¡Bienvenido a Alto Alcance CRM!</h2><p style="color:#475569;font-size:15px;line-height:1.6;margin:0 0 12px">Hola, te damos la bienvenida a <strong>{{nombre_empresa}}</strong> en Alto Alcance CRM.</p><p style="color:#475569;font-size:15px;line-height:1.6;margin:0 0 24px">Juntos llegaremos a los objetivos de tu negocio. Nuestro equipo estará contigo en cada paso para ayudarte a convertir más leads en clientes reales.</p><p style="color:#64748b;font-size:14px;margin:0 0 8px">Tu cuenta ha sido creada con el correo:</p><p style="color:#1e293b;font-size:14px;font-weight:600;background:#f1f5f9;border-radius:6px;padding:10px 16px;margin:0 0 32px">{{email}}</p><p style="color:#475569;font-size:14px;margin:0 0 16px">Para activar tu cuenta y establecer tu contraseña, haz clic en el botón a continuación:</p><div style="text-align:center;margin-bottom:32px"><a href="{{link_verificacion}}" style="display:inline-block;background:#6366F1;color:#ffffff;padding:14px 32px;border-radius:8px;text-decoration:none;font-size:15px;font-weight:600;letter-spacing:0.02em">Verificar mi cuenta</a></div><p style="color:#94a3b8;font-size:12px;line-height:1.5;margin:0">Si el botón no funciona, copia y pega este enlace en tu navegador:<br/><span style="word-break:break-all">{{link_verificacion}}</span></p></div><div style="padding:24px 40px;border-top:1px solid #e2e8f0;text-align:center"><p style="margin:0;color:#94a3b8;font-size:12px">Alto Alcance CRM &mdash; Este es un email automático, por favor no respondas.</p></div></div></body></html>',
  'welcome',
  true
WHERE NOT EXISTS (
  SELECT 1 FROM email_templates WHERE type = 'welcome' AND is_default = true
);
